### PR TITLE
Created configuration generator +NOTICES.md + Readme.md

### PR DESCRIPTION
**Pull request by ElectroJo**
Created new utility class to read config template in resources folder, then output config.json to CWD using user supplied values. Also changes the logic for checking if the config.json exists in main.kt.

If the feature is deemed unnecessary I'd still consider the change to main.kt so that it checks if the file exists before attempting to open it.
```
val file = when {
     args.isNotEmpty() -> args[0]
     File("config.json").exists() -> "config.json"
     else -> {
         logger.info("Config file was neither present as an argument or located in the CWD.")
        "config.json"
    }
}
```

Included in this pull are NOTICES.md, minor change to Readme.md (added note about NOTICES.md and added me as a contributor)

### CODE REVIEW

**Comment by ElectroJo** [comment]
Made this as a draft since its my first write of the changes and I have not looked through for possible better ways to do things.

**Comment by averen** [comment]
I don't find this to be necessary. The parser will already throw if the file is missing, which is caught by the try catch and logged.

A config template could be conceivable, but I would much rather it be dynamically generated with Klaxon.

Prompting for user input is not a good idea, startup was designed to fail-fast and detail what went wrong.

**Comment by ElectroJo** [comment]
> The parser will already throw if the file is missing, which is caught by the try catch and logged.

That's pretty fair. I just figured that a when statement to check if the file exists could be useful as other checks could be added in the future to determine where a valid config.json is.

For example, you could check if there is a valid config file in both the CWD and the location where the compiled code is:

```
val file = when {
    args.isNotEmpty() -> args[0]
    File("config.json").exists() -> "config.json"
    File(URI.create("${Sandra::class.java.getProtectionDomain().getCodeSource().getLocation()}config.json")).exists()
```
And other checks could also be applied to determine config location. I can definitely see why this isn't necessary currently though, it's just something I thought could be useful.

> A config template could be conceivable, but I would much rather it be dynamically generated with Klaxon.

Yeah, generating the template from the values supplied in com.sandrabot.sandra.config.RedisConfig, com.sandrabot.sandra.managers.CredentialManager, etc would have been more elegant. I didn't do it that way for a few reasons that I won't go into since they are obsolete if a module to generate config.json isn't wanted.

That being said the code could be easily refactored to get the values from those sources and create a template.json if the correct command line argument is supplied, e.g.:
```java -cp "sandra.jar" com.sandrabot.sandra.MainKt --GenerateConfigTemplate```

Speaking of a command line arguments:

>Prompting for user input is not a good idea, startup was designed to fail-fast and detail what went wrong.

Adding a command line argument similar to how a custom config is supplied would solve this issue.

I know that currently you just use args[NUMBER] to get values from command line arguments, however it wouldn't be hard for me to implement a function that takes uniformly formatted command line arguments and puts them in-memory as a JsonObject for reference later. 

An example of this would be ```java -cp "sandra.jar" com.sandrabot.sandra.MainKt --GenerateConfigTemplate=True --config="C:\Users\Joey\Documents\GitHub\sandra\config.json"```

into 
```
{
    "--config":"C:\Users\Joey\Documents\GitHub\sandra\config.json",
    "--GenerateConfigTemplate":True
}
```
This would allow command line arguments to be supplied in any order as they would no longer be referenced by their indice `args[0]` but would instead be referenced by their JsonObject key `Arguments["--config"]`


Edit: Or there are tons of other ways to handle arguments. I was just spitballing ideas since I do think some sort of config template generation would be useful, whether it has user-inputted values or not.

**Comment by averen** [comment]
This has been addressed by commit [11c1678](https://github.com/sandrabot/sandra/commit/11c16788420afd7d366994fe258041c783bbf862).

**Pull request closed without merging**
